pip install pandas

- differnet methods to create a dataset
- reading dataset from external sources
- basic insights of dataset
- selection of data
    - row wise selection
    - column wise selection
- Data Cleaning and manipulation

In [272]:
import pandas as pd

In [273]:
movies = {
    'title' : ['PK','DDLJ','I','RRR'],
    'year' : [2014, 1995, 2015, 2022],
    'ratings' : [8.1, 8.2, 7.5, 8.3]
}
df = pd.DataFrame(movies)
df

  title  year  ratings
0    PK  2014      8.1
1  DDLJ  1995      8.2
2     I  2015      7.5
3   RRR  2022      8.3

In [274]:
#save the dataframe to a csv file
df.to_csv('movies.csv', index=False) #index=False means we don't want to save the index column in the csv file

In [275]:
df

  title  year  ratings
0    PK  2014      8.1
1  DDLJ  1995      8.2
2     I  2015      7.5
3   RRR  2022      8.3

In [276]:
df = pd.read_csv('kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [277]:
df.head() #first 5 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [278]:
df.head(2)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639

In [279]:
df.tail() #last 5 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [280]:
df.tail(2) #last 2 rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [281]:
df.sample(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
17754,9512501400,20140902T000000,447000.0,3,1.0,1270,8800,1.0,0,0,...,7,1270,0,1968,0,98052,47.6703,-122.150,1560,8250
9677,2425059144,20150213T000000,607500.0,4,2.5,2110,13939,1.0,0,0,...,8,1270,840,1978,0,98008,47.6431,-122.113,2140,8882
1558,7214700160,20140509T000000,610000.0,3,3.0,2480,45302,1.0,0,0,...,8,1620,860,1976,0,98077,47.7591,-122.073,1260,14100
4427,4047200265,20140811T000000,325000.0,2,1.0,1100,17817,1.0,0,0,...,7,620,480,1980,0,98019,47.7728,-121.900,1790,20009
3583,1274500300,20140623T000000,200000.0,3,1.5,1090,9600,1.0,0,0,...,7,1090,0,1968,0,98042,47.3639,-122.109,1240,9620

In [282]:
df.info() #gives information about data in concise manner

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [283]:
df.describe() #gives statistical information about the data

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [284]:
df.columns #gives the column names of the dataframe

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [285]:
df.columns.tolist() #gives the column names of the dataframe in list format

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [286]:
df.isnull().sum() #gives the count of null values in each column

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

- row wise selection
    - iloc : index based selection
    - loc : label based selection
- column wise selection
    - single columns selection
        - dictionary like selection
        - object like selection
    - multiple column selection
        - dictionary like selection

In [287]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [288]:
df.iloc[0] #gives the first row of the dataframe

id                    7129300520
date             20141013T000000
price                   221900.0
bedrooms                       3
bathrooms                    1.0
sqft_living                 1180
sqft_lot                    5650
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  1180
sqft_basement                  0
yr_built                    1955
yr_renovated                   0
zipcode                    98178
lat                      47.5112
long                    -122.257
sqft_living15               1340
sqft_lot15                  5650
Name: 0, dtype: object

In [289]:
df.iloc[5]

id                    7237550310
date             20140512T000000
price                  1225000.0
bedrooms                       4
bathrooms                    4.5
sqft_living                 5420
sqft_lot                  101930
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                         11
sqft_above                  3890
sqft_basement               1530
yr_built                    2001
yr_renovated                   0
zipcode                    98053
lat                      47.6561
long                    -122.005
sqft_living15               4760
sqft_lot15                101930
Name: 5, dtype: object

In [290]:
df.iloc[1:6] #gives rows from index 1 to 5 (6 is exclusive)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930

In [291]:
df.iloc[1:11:2]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [292]:
df.iloc[[3,5,11,13]] #gives rows with index 3,5,11,13

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
11,9212900260,20140527T000000,468000.0,2,1.00,1160,6000,1.0,0,0,...,7,860,300,1942,0,98115,47.6900,-122.292,1330,6000
13,6054650070,20141007T000000,400000.0,3,1.75,1370,9680,1.0,0,0,...,7,1370,0,1977,0,98074,47.6127,-122.045,1370,10208

In [293]:
df.iloc[[2,5],[1,3]] #gives rows with index 2 and 5 and columns with index 1 and 3

              date  bedrooms
2  20150225T000000         2
5  20140512T000000         4

In [294]:
df.iloc[1:6,1:5] #gives rows from index 1 to 5 and columns from index 1 to 4 (5 is exclusive)

              date      price  bedrooms  bathrooms
1  20141209T000000   538000.0         3       2.25
2  20150225T000000   180000.0         2       1.00
3  20141209T000000   604000.0         4       3.00
4  20150218T000000   510000.0         3       2.00
5  20140512T000000  1225000.0         4       4.50

In [295]:
df = df.set_index('id') #set the index of the dataframe to the 'id' column
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [296]:
df.loc[6414100192]

date             20141209T000000
price                   538000.0
bedrooms                       3
bathrooms                   2.25
sqft_living                 2570
sqft_lot                    7242
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  2170
sqft_basement                400
yr_built                    1951
yr_renovated                1991
zipcode                    98125
lat                       47.721
long                    -122.319
sqft_living15               1690
sqft_lot15                  7639
Name: 6414100192, dtype: object

In [297]:
df.loc[:1954400510] #end range is inclusive in loc

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

DATA CLEANING
- dropping rows and column
- renaming column names
- changing data type of a column
- dropping missing values
- handling missing values
- checking duplicates
- dropping duplicates
- checking unique values
- count of unique values
- frequency count of a value
- sorting values

In [298]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [299]:
df = df.drop(columns=['sqft_living15','sqft_lot15'])
df.columns #drop the columns 'sqft_living15' and 'sqft_lot15' from the dataframe

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='object')

In [300]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045

In [301]:
df = df.drop(labels = [6414100192, 1954400510], axis = 0) #drop the rows with index 6414100192 and 1954400510 from the dataframe
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005
1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327

In [302]:
#renaming columns in the dataframe
renamed_cols = {
    'lat' : 'latitude',
    'long' : 'longitude',
}
df = df.rename(columns=renamed_cols)
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'latitude',
       'longitude'],
      dtype='object')

In [303]:
cols = list(df.columns)
cols[0] = 'ID'
df.columns = cols

In [304]:
df.columns

Index(['ID', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'latitude',
       'longitude'],
      dtype='object')

In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21611 entries, 7129300520 to 1523300157
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21611 non-null  object
 1   price          21611 non-null  float64
 2   bedrooms       21611 non-null  int64
 3   bathrooms      21611 non-null  float64
 4   sqft_living    21611 non-null  int64
 5   sqft_lot       21611 non-null  int64
 6   floors         21611 non-null  float64
 7   waterfront     21611 non-null  int64
 8   view           21611 non-null  int64
 9   condition      21611 non-null  int64
 10  grade          21611 non-null  int64
 11  sqft_above     21611 non-null  int64
 12  sqft_basement  21611 non-null  int64
 13  yr_built       21611 non-null  int64
 14  yr_renovated   21611 non-null  int64
 15  zipcode        21611 non-null  int64
 16  latitude       21611 non-null  float64
 17  longitude      21611 non-null  float64
dtypes: float64(5), int64(12), object(1)
memory usage: 3.1+ MB

In [306]:
#changing datatype
df = df.astype({'bedrooms': 'float64'})
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 21611 entries, 7129300520 to 1523300157
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             21611 non-null  object
 1   price          21611 non-null  float64
 2   bedrooms       21611 non-null  float64
 3   bathrooms      21611 non-null  float64
 4   sqft_living    21611 non-null  int64
 5   sqft_lot       21611 non-null  int64
 6   floors         21611 non-null  float64
 7   waterfront     21611 non-null  int64
 8   view           21611 non-null  int64
 9   condition      21611 non-null  int64
 10  grade          21611 non-null  int64
 11  sqft_above     21611 non-null  int64
 12  sqft_basement  21611 non-null  int64
 13  yr_built       21611 non-null  int64
 14  yr_renovated   21611 non-null  int64
 15  zipcode        21611 non-null  int64
 16  latitude       21611 non-null  float64
 17  longitude      21611 non-null  float64
dtypes: float64(6), int64(11), object(1)
memory usage: 3.1+ MB

,ID,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,latitude,longitude
id,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3.0,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005
1321400060,20140627T000000,257500.0,3.0,2.25,1715,6819,2.0,0,0,3,7,1715,0,1995,0,98003,47.3097,-122.327

pip install seaborn

In [307]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\pc\miniconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\pc\miniconda3\lib\site-packages (from seaborn) (2.4.0)
Requirement already satisfied: pandas>=1.2 in c:\users\pc\miniconda3\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\pc\miniconda3\lib\site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\pc\miniconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\miniconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\miniconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\pc\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [308]:
import seaborn as sns
sns.get_dataset_names() #gives the list of available datasets in seaborn

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [309]:
titanic = sns.load_dataset('titanic') #load the titanic dataset from seaborn
titanic.isnull().sum() #gives the count of null values in each column of the titanic dataset

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

- When a column has <40% missing values of the data, then we simply remove that  column
- When a column has >40% missing values of data, then we handle those missing values means we replace those missing values with any number
    - there are teo type of columns in any dataset - CATAGORICAL & NUMERICAL
    - When the column is numerical, we always repalce the null values with the column mean(average)
    - When the column is categorical, we always replace the null values with most frequent(mode) values

In [310]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [311]:
titanic = titanic.dropna(subset=['embarked']) #drop the rows where the 'embarked' column has null values
titanic.isnull().sum() #gives the count of null values in each column

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [312]:
avg_age = round(titanic['age'].mean()) #calculate the average age of passengers in the titanic dataset
print(avg_age)

30

In [313]:
#replace null values with avg_age
titanic['age'] = titanic['age'].fillna(avg_age) #replace null values in the 'age' column with avg_age
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [314]:
#checking duplicate values
duplicates = titanic[titanic.duplicated()]
print(duplicates)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
47          1       3  female  30.0      0      0   7.7500        Q   Third
76          0       3    male  30.0      0      0   7.8958        S   Third
77          0       3    male  30.0      0      0   8.0500        S   Third
87          0       3    male  30.0      0      0   8.0500        S   Third
95          0       3    male  30.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
870         0       3    male  26.0      0      0   7.8958        S   Third
877         0       3    male  19.0      0      0   7.8958        S   Third
878         0       3    male  30.0      0      0   7.8958        S   Third
884         0       3    male  25.0      0      0   7.0500        S   Third
886         0       2    male  27.0      0      0  13.0000        S  Second

       who  adult_male deck  embark_town alive  alone
47   woman       False  NaN   Queenstown   yes   True
76     man        True  NaN  Southampton    no   True
77     man        True  NaN  Southampton    no   True
87     man        True  NaN  Southampton    no   True
95     man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
870    man        True  NaN  Southampton    no   True
877    man        True  NaN  Southampton    no   True
878    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True

[113 rows x 15 columns]

In [315]:
#dropping duplicates
titanic.drop_duplicates()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [316]:
titanic["age"].unique()

array([22.  , 38.  , 26.  , 35.  , 30.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [317]:
#frequence of values in a categorical column
titanic['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [334]:
titanic['embark_town'].value_counts().idxmax()

'Southampton'

In [335]:
titanic['embark_town'].value_counts().idxmin()

'Queenstown'

In [318]:
df.sort_index()

,ID,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,latitude,longitude
id,,,,,,,,,,,,,,,,,,
1000102,20150422T000000,300000.0,6.0,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214
1000102,20140916T000000,280000.0,6.0,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214
1200019,20140508T000000,647500.0,4.0,1.75,2060,26036,1.0,0,0,4,8,1160,900,1947,0,98166,47.4444,-122.351
1200021,20140811T000000,400000.0,3.0,1.00,1460,43000,1.0,0,0,3,7,1460,0,1952,0,98166,47.4434,-122.347
2800031,20150401T000000,235000.0,3.0,1.00,1430,7599,1.5,0,0,4,6,1010,420,1930,0,98168,47.4783,-122.265
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9842300095,20140725T000000,365000.0,5.0,2.00,1600,4168,1.5,0,0,3,7,1600,0,1927,0,98126,47.5297,-122.381
9842300485,20150311T000000,380000.0,2.0,1.00,1040,7372,1.0,0,0,5,7,840,200,1939,0,98126,47.5285,-122.378
9842300540,20140624T000000,339000.0,3.0,1.00,1100,4128,1.0,0,0,4,7,720,380,1942,0,98126,47.5296,-122.379
9895000040,20140703T000000,399900.0,2.0,1.75,1410,1005,1.5,0,0,3,9,900,510,2011,0,98027,47.5446,-122.018
9900000190,20141030T000000,268950.0,3.0,1.00,1320,8100,1.0,0,0,3,6,880,440,1943,0,98166,47.4697,-122.351

DATA MANIPULATION

In [319]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [320]:
#Adding a new column
titanic = titanic.assign(Discount=titanic["fare"]*0.10)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [321]:
titanic['fare'] = titanic['fare'].apply(lambda x:x*1.05)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [322]:
titanic["embarked"] = titanic["embarked"].map({
    "S" : "Southampton",
    "C" : "Cherbourg",
    "Q" : "Queenstown"
})
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [323]:
titanic.groupby("embarked")["fare"].mean()

embarked
Cherbourg      62.951851
Queenstown     13.939831
Southampton    28.433802
Name: fare, dtype: float64

In [325]:
titanic.groupby("sex")["fare"].max()

sex
female    537.94566
male      537.94566
Name: fare, dtype: float64

In [329]:
#data filtering
titanic[titanic["survived"] == 1]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.586250,Cherbourg,Third,child,False,NaN,Cherbourg,yes,True,0.72250
879,1,1,female,56.0,0,1,87.316215,Cherbourg,First,woman,False,C,Cherbourg,yes,False,8.31583
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000

In [330]:
titanic[titanic['sex'] == "female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
882,0,3,female,22.0,0,0,11.042535,Southampton,Third,woman,False,NaN,Southampton,no,True,1.05167
885,0,3,female,39.0,0,5,30.581250,Queenstown,Third,woman,False,NaN,Queenstown,no,False,2.91250
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500

In [333]:
#sorting values
titanic.sort_values('fare',ascending=False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Discount
679,1,1,male,36.0,0,1,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,False,51.23292
258,1,1,female,35.0,0,0,537.94566,Cherbourg,First,woman,False,NaN,Cherbourg,yes,True,51.23292
737,1,1,male,35.0,0,0,537.94566,Cherbourg,First,man,True,B,Cherbourg,yes,True,51.23292
341,1,1,female,24.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
88,1,1,female,23.0,3,2,276.15000,Southampton,First,woman,False,C,Southampton,yes,False,26.30000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,0,3,male,36.0,0,0,0.00000,Southampton,Third,man,True,NaN,Southampton,no,True,0.00000
263,0,1,male,40.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
277,0,2,male,30.0,0,0,0.00000,Southampton,Second,man,True,NaN,Southampton,no,True,0.00000
815,0,1,male,30.0,0,0,0.00000,Southampton,First,man,True,B,Southampton,no,True,0.00000
822,0,1,male,38.0,0,0,0.00000,Southampton,First,man,True,NaN,Southampton,no,True,0.00000